name: Deploy to Google Cloud

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: 'beta'

    - name: Configure Docker authentication
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and deploy using Cloud Build
      id: deploy
      run: |
        gcloud builds submit \
          --config=deploy/cloudbuild.yaml \
          --timeout=1800s \
          --substitutions=_REGION=${{ env.REGION }},_REPOSITORY=${{ env.REPOSITORY }},_SERVICE_NAME=${{ env.SERVICE_NAME }}

    - name: Wait for deployment
      run: |
        echo "Waiting for service to be ready..."
        sleep 30

    - name: Verify deployment
      run: |
        MAX_RETRIES=5
        RETRY_COUNT=0

        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format="value(status.url)")
          echo "Deployment URL: $SERVICE_URL"

          if curl -f "$SERVICE_URL/health" > /dev/null 2>&1; then
            echo "✅ Deployment verified successfully!"
            exit 0
          else
            echo "Attempt $((RETRY_COUNT+1))/$MAX_RETRIES: Service not ready yet, waiting..."
            RETRY_COUNT=$((RETRY_COUNT+1))
            sleep 30
          fi
        done

        echo "❌ Deployment verification failed after $MAX_RETRIES attempts"
        exit 1
